version: "3.6"

services:
  app:
    build: .
    command: npm run dev
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      # Sync working directory during development
  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
